data: config/data/data_config.yml

preprocess:
  numerical:
    conf_path: config/preprocessing/standard_scaler.yml
    cols:
      - powerPS
      - kilometer
      - age_of_car

  categorical:
    conf_path: config/preprocessing/ordinal_encoder.yml
    cols:
      - abtest
      - vehicleType
      - gearbox
      - model
      - fuelType
      - brand

  target:
    conf_path: config/preprocessing/standard_scaler.yml

model:
  name: GradientBoosting
  kwargs:
    loss: squared_error
    learning_rate: 0.1
    n_estimators: 400
    subsample: 1.0
    criterion: friedman_mse
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0
    max_depth: 3
    min_impurity_decrease: 0.0
    init: null
    random_state: 42
    max_features: 1.0
    alpha: 0.9
    verbose: 1
    max_leaf_nodes: null
    warm_start: False
    validation_fraction: 0.1
    n_iter_no_change: null
    tol: 1.0e-4
    ccp_alpha: 0.0
